// 实时职位数据 —— 由 WorkBuddy 定时自动化每日抓取并更新
// 数据来源：公开招聘平台搜索聚合（Boss直聘 / 猎聘 / 官方招聘官网 / 聚合站等）
// 注意：仅基于公开搜索结果，薪资为平台公开区间或「面议」，非全量实时数据。

// 细分方向（与「单独成列」对应，便于前端按方向筛选）
export type JobDirection = "AI Agent" | "大模型算法" | "RAG" | "多模态" | "Agent Infra"

export interface Job {
  company: string
  title: string
  direction: JobDirection
  location: string
  salary: string
  seniority: string
  education: string
  source: string
  link: string
  skills: string[]
}

// 最近一次抓取日期（YYYY-MM-DD）
export const jobsLastUpdated = "2026-09-24"

// 招聘方聚焦方向：大厂 + 头部 AI 独角兽
export const jobFocus = {
  label: "大厂 · 头部 AI 独角兽",
  companies: [
    "字节跳动", "腾讯", "阿里巴巴", "百度", "美团", "快手", "小红书", "蚂蚁集团", "华为", "小米",
    "深度求索 DeepSeek", "月之暗面 Moonshot", "MiniMax", "智谱 AI", "阶跃星辰 StepFun", "百川智能", "零一万物", "面壁智能",
  ],
}

// 抓取来源与统计口径
export const jobsStats = {
  tracked: 137, // 聚合站跟踪的 AI Agent Engineer 职位数
  companies: 76, // 覆盖公司数
  demandGrowth: "470%", // 大模型算法工程师需求同比增速
  talentGap: "8.7 万", // 大模型算法岗位人才缺口
}

// 各 AI 工程岗位薪资参考（月薪下限-上限 / 年薪参考），来源：Boss直聘·猎聘·职友集·脉脉 综合
export const salaryRanges: { role: string; monthly: string; annual: string }[] = [
  { role: "大模型算法工程师", monthly: "40-130K+", annual: "50-200 万" },
  { role: "LLMOps 工程师", monthly: "35-70K", annual: "42-84 万" },
  { role: "AI Agent 开发工程师", monthly: "15-55K", annual: "18-66 万" },
  { role: "RAG 工程师", monthly: "18-50K", annual: "22-60 万" },
]

// 当前聚合到的职位（聚焦大厂 + 头部 AI 独角兽，由定时任务每日覆盖更新）
// 抓取日期：2026-09-24，覆盖 18 家目标公司，共 25 条公开在招岗位
export const jobs: Job[] = [
  {
    company: "字节跳动",
    title: "大模型算法工程师(Agent 方向)-火山引擎",
    direction: "AI Agent",
    location: "北京",
    salary: "面议",
    seniority: "3-5 年",
    education: "本科+",
    source: "BOSS直聘",
    link: "https://www.zhipin.com/job_detail/49c942e5832d84da03153tu4ElNT.html",
    skills: ["客服&营销 Agent", "语音 Agent", "Agent Search/Coding/Tool Use", "GUI Agent", "数据建设", "模型优化"],
  },
  {
    company: "字节跳动",
    title: "大模型算法工程师-国际支付(杭州)",
    direction: "AI Agent",
    location: "杭州",
    salary: "面议",
    seniority: "2 年+",
    education: "本科+",
    source: "BOSS直聘",
    link: "https://m.zhipin.com/job_detail/e4944e39dc912d950nR-09i9FlBX.html",
    skills: ["SFT/RLVR/Agent RL", "智能催收/客服/运维/审核 Agent", "ReAct/Plan-Act", "Multi-Agent", "Test-Time-Scaling", "后训练"],
  },
  {
    company: "腾讯",
    title: "智能体-Agent Harness 全栈工程师(WorkBuddy/CodeBuddy)",
    direction: "Agent Infra",
    location: "深圳",
    salary: "面议",
    seniority: "5 年+",
    education: "本科+",
    source: "腾讯招聘",
    link: "https://careers.tencent.com/jobdesc.html?postId=2098252336337170432",
    skills: ["Agent Harness 全栈", "Context Engineering", "Long-term Memory", "Multi-Agent Coordination", "沙箱执行", "工具注册中心/评测后台"],
  },
  {
    company: "腾讯",
    title: "混元AI Agent Harness Engineer（北京/深圳）",
    direction: "Agent Infra",
    location: "北京 / 深圳",
    salary: "面议",
    seniority: "校招/实习",
    education: "博士+",
    source: "牛企直聘",
    link: "https://campus.niuqizp.com/job-vYm5zMMZ5.html",
    skills: ["Agent Harness", "Agent 后训练", "强化学习框架", "Agent 评测 Infra", "沙盒平台", "VLM 测评"],
  },
  {
    company: "阿里巴巴",
    title: "千问事业部-智能体平台高级研发工程师/专家",
    direction: "Agent Infra",
    location: "北京 / 杭州 / 广州",
    salary: "面议",
    seniority: "3 年",
    education: "本科+",
    source: "猎聘",
    link: "https://www.liepin.com/job/1985701165.shtml",
    skills: ["智能体开发范式", "RAG/记忆/Agent 机制", "LangChain/Coze/Dify", "多智能体研发", "中间件架构", "千万级应用架构"],
  },
  {
    company: "阿里巴巴",
    title: "千问事业部-广告营销创意AIGC算法工程师(图像、视频方向)",
    direction: "多模态",
    location: "北京",
    salary: "面议",
    seniority: "3 年",
    education: "硕士+",
    source: "夸克招聘",
    link: "https://talent.quark.cn/off-campus/position-detail?lang=zh&positionId=100018560006",
    skills: ["多模态大模型 MLLM", "Diffusion/ControlNet/LoRA", "AI Agent 系统", "工具调用/任务编排", "营销素材生成", "广告创意自动化"],
  },
  {
    company: "百度",
    title: "Agent引擎开发工程师(J103885)",
    direction: "Agent Infra",
    location: "北京",
    salary: "40-50k·16薪",
    seniority: "3-5 年",
    education: "本科+",
    source: "猎聘",
    link: "https://m.liepin.com/job/1985695967.shtml",
    skills: ["Agent 运行引擎", "Skills 插件系统", "长期记忆 Memory", "多模型路由", "沙箱/权限校验", "human-in-the-loop"],
  },
  {
    company: "百度",
    title: "Agent架构研发工程师",
    direction: "AI Agent",
    location: "北京",
    salary: "面议",
    seniority: "实习/校招",
    education: "本科+",
    source: "BOSS直聘",
    link: "https://m.zhipin.com/job_detail/fc819106927a2e5e03153t--ElFT.html",
    skills: ["自研 Agent 架构", "Coding/Deep Research", "垂类场景能力", "业务线提效", "新型人机交互", "大模型训练推理部署"],
  },
  {
    company: "美团",
    title: "履约技术-Agent工程开发",
    direction: "AI Agent",
    location: "北京",
    salary: "面议",
    seniority: "3 年",
    education: "本科+",
    source: "美团招聘",
    link: "https://zhaopin.meituan.com/web/position/detail?jobUnionId=4767045690",
    skills: ["AutoResearch Agent", "代码理解与修改", "工具调用/上下文管理", "任务评估/失败分析", "AI-SDLC", "长链任务执行"],
  },
  {
    company: "美团",
    title: "Agent 开发工程师(全栈)",
    direction: "AI Agent",
    location: "北京",
    salary: "面议",
    seniority: "2 年",
    education: "本科+",
    source: "美团招聘",
    link: "https://zhaopin.meituan.com/web/position/detail?jobUnionId=4647373928",
    skills: ["Agent 架构设计", "任务分解/工具调用", "多 Agent 编排", "Skill 运行时", "长链任务可靠性", "状态持久化/断点续跑"],
  },
  {
    company: "蚂蚁集团",
    title: "大模型Agent算法应用工程师-杭州",
    direction: "AI Agent",
    location: "杭州",
    salary: "面议",
    seniority: "3-5 年",
    education: "硕士+",
    source: "BOSS直聘",
    link: "https://m.zhipin.com/job_detail/575bfe6a543004640nR_2N26FlBU.html",
    skills: ["支付宝大模型应用", "用户意图理解/服务执行", "多智能体协同", "推理/规划/执行", "LLM/VLM 微调", "产业场景落地"],
  },
  {
    company: "蚂蚁集团",
    title: "大模型算法工程师—北京(急招)",
    direction: "大模型算法",
    location: "北京",
    salary: "面议",
    seniority: "5-10 年",
    education: "本科+",
    source: "BOSS直聘",
    link: "https://m.zhipin.com/job_detail/2ea002a4db2cad511Hdz29u_EFZS.html",
    skills: ["LLM 软件研发落地", "Agent/Multi-agent", "Tool Learning", "RAG", "RLHF", "领域模型全流程"],
  },
  {
    company: "阶跃星辰 StepFun",
    title: "工具开发-Agent 研发工程师",
    direction: "Agent Infra",
    location: "上海",
    salary: "30-60k·16薪",
    seniority: "3 年+",
    education: "本科+",
    source: "猎聘",
    link: "https://m.liepin.com/job/1985731289.shtml",
    skills: ["Sandbox 安全隔离", "企业知识库/Memory", "MCP + Skills", "Agent 编排", "SOP 重构为可复用 Agent", "企业数据安全治理"],
  },
  {
    company: "阶跃星辰 StepFun",
    title: "AI 应用技术负责人(Agent与记忆系统)",
    direction: "Agent Infra",
    location: "上海",
    salary: "30-60k·15薪",
    seniority: "8 年+",
    education: "本科+",
    source: "猎聘",
    link: "https://m.liepin.com/job/1985645237.shtml",
    skills: ["Agent 核心逻辑", "长期/短期记忆", "上下文压缩", "Function Calling/MCP", "多 Agent 协作", "端云协同与模型路由"],
  },
  {
    company: "快手",
    title: "大模型推理工程师(LLM Inference)",
    direction: "大模型算法",
    location: "北京 / 上海 / 深圳 / 杭州",
    salary: "面议",
    seniority: "3-5 年",
    education: "本科+",
    source: "BOSS直聘",
    link: "https://refund.zhipin.com/job_detail/4cb068be1ba7382a0nV-2Ny8FlFX.html",
    skills: ["大模型推理引擎", "KV Cache 管理", "Batching/Scheduling", "算子优化/量化加速", "强化学习 RL", "混合精度"],
  },
  {
    company: "小红书",
    title: "【2027校招】AI Agent工程师(大模型 AI 应用开发方向)-审核研发",
    direction: "AI Agent",
    location: "北京 / 上海 / 杭州",
    salary: "面议",
    seniority: "校招",
    education: "本科+",
    source: "小红书官网",
    link: "https://campus.niuqizp.com/job-vkU5CaNLC.html",
    skills: ["AI Native 审核链路", "Agent Harness", "工具调用", "上下文工程", "风险感知→管控全链路", "Java"],
  },
  {
    company: "华为",
    title: "AI Agent开发工程师",
    direction: "AI Agent",
    location: "西安",
    salary: "面议",
    seniority: "实习",
    education: "本科+",
    source: "BOSS直聘",
    link: "https://www.zhipin.com/job_detail/dca658d4b6b351da0nZy2dW_ElRR.html",
    skills: ["记忆管理/自主决策/代码生成", "上下文管理/规划推理", "工具调用", "复杂任务数据管线", "Repo 级长程轨迹", "多步工具编排"],
  },
  {
    company: "小米",
    title: "座舱AI-多模态大模型算法专家/高级工程师",
    direction: "多模态",
    location: "北京",
    salary: "70-100k·18薪",
    seniority: "2-6 年",
    education: "硕士+",
    source: "猎聘",
    link: "https://m.liepin.com/job/1985710619.shtml",
    skills: ["多模态统一建模", "大模型后训练", "端云协同", "Agent 主动交互落地", "模型压缩与端侧部署", "座舱场景"],
  },
  {
    company: "深度求索 DeepSeek",
    title: "Agent弹性计算研发工程师（弹性计算 DSec）",
    direction: "Agent Infra",
    location: "北京 / 杭州",
    salary: "面议",
    seniority: "2-10 年",
    education: "本科+",
    source: "DeepSeek 官网",
    link: "http://talent.deepseek.com/",
    skills: ["Agent 弹性计算", "DSec", "沙箱隔离", "系统栈调优", "RPC/分布式", "下一代模型迭代"],
  },
  {
    company: "月之暗面 Moonshot",
    title: "资深Agent研发工程师(Kimi)",
    direction: "AI Agent",
    location: "北京 / 上海",
    salary: "面议",
    seniority: "不限",
    education: "本科+",
    source: "月之暗面招聘",
    link: "https://jobspring.pro/job/j3957053/agent-moonshot",
    skills: ["Agent 内核框架", "任务执行", "工具生态(Skills/MCP/Sandbox)", "工程基座", "CI/CD & DevOps", "Go 微服务"],
  },
  {
    company: "MiniMax",
    title: "服务端研发(Agent方向)",
    direction: "Agent Infra",
    location: "上海",
    salary: "40-60K·16薪",
    seniority: "5-10 年",
    education: "本科+",
    source: "猎聘",
    link: "https://m.liepin.com/job/1984221441.shtml",
    skills: ["AI Agent 与 AI APP", "任务调度", "上下文管理", "工具调用", "数据链路", "高并发"],
  },
  {
    company: "智谱 AI",
    title: "GLM团队-后训练算法工程师(26届校招)",
    direction: "AI Agent",
    location: "北京",
    salary: "面议",
    seniority: "校招",
    education: "硕士+",
    source: "BOSS直聘",
    link: "https://m.zhipin.com/job_detail/bd77a679c56b2e8e03Nz3du0F1pV.html",
    skills: ["Agentic LLM", "指令遵循", "长上下文理解", "长程交互/任务规划", "Coding Agent", "Search Agent"],
  },
  {
    company: "百川智能",
    title: "【源点顶尖人才计划】大模型算法工程师(Agent算法)",
    direction: "AI Agent",
    location: "北京",
    salary: "面议",
    seniority: "应届",
    education: "硕士+",
    source: "百川智能招聘",
    link: "https://careers.baichuan-inc.com/origin-program",
    skills: ["Agent 核心算法", "工具使用", "多模态对齐", "后训练 SFT/RL", "合成数据流水线", "Agent 能力评测"],
  },
  {
    company: "零一万物",
    title: "AI算法工程师(智能体)",
    direction: "AI Agent",
    location: "北京",
    salary: "27-45K·14薪",
    seniority: "3 年+",
    education: "硕士+",
    source: "猎聘",
    link: "https://m.liepin.com/job/1984995285.shtml",
    skills: ["Agent 架构", "Prompt/CoT/ToT", "Tool Use", "SFT/DPO", "多智能体协同", "RAG"],
  },
  {
    company: "面壁智能",
    title: "大模型算法工程师-行业应用",
    direction: "AI Agent",
    location: "上海",
    salary: "面议",
    seniority: "1-3 年",
    education: "硕士+",
    source: "BOSS直聘",
    link: "https://m.zhipin.com/job_detail/a9e343402386d4200nZ42Nu_GVBS.html",
    skills: ["SFT/RL", "Agent/Multi-Agent", "RAG", "文本与多模态大模型", "前沿训练优化", "行业应用落地"],
  },
]
