// 实时职位数据 —— 由 WorkBuddy 定时自动化每日抓取并更新
// 数据来源：公开招聘平台搜索聚合（Boss直聘 / 猎聘 / 官方招聘官网 / 聚合站等）
// 注意：仅基于公开搜索结果，薪资为平台公开区间或「面议」，非全量实时数据。

// 细分方向（与「单独成列」对应，便于前端按方向筛选）
export type JobDirection = "AI Agent" | "大模型算法" | "RAG" | "多模态" | "Agent Infra"

export interface Job {
  company: string
  title: string
  direction: JobDirection
  location: string
  salary: string
  seniority: string
  education: string
  source: string
  link: string
  skills: string[]
}

// 最近一次抓取日期（YYYY-MM-DD）
export const jobsLastUpdated = "2026-10-03"

// 招聘方聚焦方向：大厂 + 头部 AI 独角兽
export const jobFocus = {
  label: "大厂 · 头部 AI 独角兽",
  companies: [
    "字节跳动", "腾讯", "阿里巴巴", "百度", "美团", "快手", "小红书", "蚂蚁集团", "华为", "小米",
    "深度求索 DeepSeek", "月之暗面 Moonshot", "MiniMax", "智谱 AI", "阶跃星辰 StepFun", "百川智能", "零一万物", "面壁智能",
  ],
}

// 抓取来源与统计口径
export const jobsStats = {
  tracked: 137, // 聚合站跟踪的 AI Agent Engineer 职位数
  companies: 76, // 覆盖公司数
  demandGrowth: "470%", // 大模型算法工程师需求同比增速
  talentGap: "8.7 万", // 大模型算法岗位人才缺口
}

// 各 AI 工程岗位薪资参考（月薪下限-上限 / 年薪参考），来源：Boss直聘·猎聘·职友集·脉脉 综合
export const salaryRanges: { role: string; monthly: string; annual: string }[] = [
  { role: "大模型算法工程师", monthly: "40-130K+", annual: "50-200 万" },
  { role: "LLMOps 工程师", monthly: "35-70K", annual: "42-84 万" },
  { role: "AI Agent 开发工程师", monthly: "15-55K", annual: "18-66 万" },
  { role: "RAG 工程师", monthly: "18-50K", annual: "22-60 万" },
]

// 当前聚合到的职位（聚焦大厂 + 头部 AI 独角兽，由定时任务每日覆盖更新）
// 抓取日期：2026-10-03，覆盖 18 家目标公司，共 25 条公开在招岗位
export const jobs: Job[] = [
  {
    company: "字节跳动",
    title: "AI Agent研发工程师(记忆&自进化)-产品研发和工程架构",
    direction: "AI Agent",
    location: "深圳",
    salary: "面议",
    seniority: "经验不限",
    education: "本科+",
    source: "字节跳动招聘",
    link: "https://jobs.bytedance.com/experienced/position/7633443559517161781/detail?sourceJobId=7512352196127574290",
    skills: ["Knowledge & Memory", "Self-evolving & Evaluator", "Skills & Tools", "上下文工程", "长程任务执行", "Agent 平台研发", "AI Coding"],
  },
  {
    company: "字节跳动",
    title: "LLM应用/Agent/AI平台研发工程师-Data",
    direction: "AI Agent",
    location: "上海",
    salary: "面议",
    seniority: "经验不限",
    education: "本科+",
    source: "字节跳动招聘",
    link: "https://jobs.bytedance.com/experienced/position/7634456497736534325/detail?sourceJobId=7623421136101099829",
    skills: ["大模型与 Agent 应用核心链路", "Prompt 组织与 Agent 编排", "错例归因与回归验证", "可观测与感知基础设施", "AI 决策降本提效", "效果/成本/性能权衡"],
  },
  {
    company: "腾讯",
    title: "智能体-Agent Harness 全栈工程师-WorkBuddy/CodeBuddy",
    direction: "Agent Infra",
    location: "深圳",
    salary: "面议",
    seniority: "5 年+",
    education: "本科+",
    source: "腾讯招聘",
    link: "https://careers.tencent.com/jobdesc.html?postId=2098252336337170432",
    skills: ["Agent Harness 全栈", "执行轨迹回放", "上下文编排器", "工具注册中心", "评测数据后台", "Sandbox/可观测性/Token Efficiency"],
  },
  {
    company: "腾讯",
    title: "混元AI Agent Harness Engineer（北京/深圳）",
    direction: "Agent Infra",
    location: "北京 / 深圳",
    salary: "面议",
    seniority: "2 年+",
    education: "本科+",
    source: "腾讯招聘",
    link: "https://careers.tencent.com/jobdesc.html?postId=2052685072754196480",
    skills: ["Agent 全链路 Tracing & Observability", "自动化 eval pipeline", "Agent Debugging 工具", "标注/SBS 评测/数据管道", "Agentic Coding", "大模型与 Agent 协同工程化"],
  },
  {
    company: "阿里巴巴",
    title: "千问事业部-大模型应用算法工程师(Agent 方向)",
    direction: "AI Agent",
    location: "北京",
    salary: "面议",
    seniority: "经验不限",
    education: "硕士+",
    source: "猎聘",
    link: "https://m.liepin.com/job/1971878441.shtml",
    skills: ["广告投放 Agent", "Skills 自主进化体系", "Agent Memory/经验复盘", "Harness 基础设施(上下文/规划/多Agent)", "HITL 人机协同", "Agent 后训练与强化学习"],
  },
  {
    company: "阿里巴巴",
    title: "千问事业部-多模态检索与agent算法专家",
    direction: "多模态",
    location: "杭州 / 北京",
    salary: "面议",
    seniority: "1 年+",
    education: "硕士+",
    source: "夸克招聘",
    link: "https://talent.quark.cn/off-campus/position-detail?lang=zh&positionId=100025920004",
    skills: ["多模态检索", "智能体搜索 Agentic Search", "多模态 RAG", "VLM", "语义匹配", "内容理解"],
  },
  {
    company: "百度",
    title: "大模型算法工程师(文心智能体策略优化) J94940",
    direction: "AI Agent",
    location: "北京",
    salary: "面议",
    seniority: "经验不限",
    education: "本科+",
    source: "百度招聘",
    link: "https://talent.baidu.com/jobs/detail/SOCIAL/1d680ec9-74a3-4043-89ce-c6201647b0fa",
    skills: ["文心智能体策略优化", "提示词工程/大模型定制调优", "智能体内容生成质量评估", "搜索场景下分发形态", "RAG 与强化学习", "多模态内容评估"],
  },
  {
    company: "百度",
    title: "智能体策略研发工程师 J91825",
    direction: "AI Agent",
    location: "北京",
    salary: "面议",
    seniority: "经验不限",
    education: "硕士+",
    source: "百度招聘",
    link: "https://talent.baidu.com/jobs/detail/SOCIAL/3be84d76-38d2-40ff-ac4f-9aaef403179e",
    skills: ["智能体与大模型技术研发", "交互策略设计", "RAG / 大模型后训练", "智能体富媒体内容理解", "搜索与交互满足", "Agentic RL"],
  },
  {
    company: "美团",
    title: "智能体算法工程师(商业智能方向)",
    direction: "AI Agent",
    location: "北京 / 上海",
    salary: "面议",
    seniority: "经验不限",
    education: "本科+",
    source: "美团招聘",
    link: "https://zhaopin.meituan.com/web/position/detail?highlightType=social&jobUnionId=4521454594",
    skills: ["自主智能体操盘营销预算", "Skill 体系构建与自进化", "智能体框架(架构/推理成本/长期记忆)", "模型全链路训练与调优", "SFT/RL 效果评测", "AI-Native 工作范式"],
  },
  {
    company: "美团",
    title: "AI Agent算法工程师(商家Agent全链路)",
    direction: "Agent Infra",
    location: "上海",
    salary: "面议",
    seniority: "经验不限",
    education: "本科+",
    source: "牛企直聘",
    link: "https://jobs.niuqizp.com/job-vym5Natnz.html",
    skills: ["商家 Agent 全链路", "意图理解/任务规划/记忆", "Agent Harness 优化", "SFT/DPO/RLHF/GRPO", "领域知识挖掘", "Agent 评测体系"],
  },
  {
    company: "蚂蚁集团",
    title: "算法工程师-智能体/大模型",
    direction: "AI Agent",
    location: "杭州",
    salary: "面议",
    seniority: "3-5 年",
    education: "硕士+",
    source: "BOSS直聘",
    link: "https://m.zhipin.com/job_detail/4201d5a566e36d330nZ83di_ElBT.html",
    skills: ["RAG 检索增强", "Agent 复杂规划执行", "LLM 可控知识生产", "LLM 推理加速", "NLP 大模型前沿", "业务落地"],
  },
  {
    company: "蚂蚁集团",
    title: "垂类模型后训练科学家-【AGI专项】",
    direction: "AI Agent",
    location: "北京 / 上海 / 杭州",
    salary: "面议",
    seniority: "3 年+",
    education: "本科+",
    source: "蚂蚁集团招聘",
    link: "https://talent.antgroup.com/off-campus-position?positionId=26010708281301",
    skills: ["垂类后训练 SFT/对齐", "Reward 模型", "Agentic-RL 仿真环境", "API 对接/多轮决策", "金融事实性/合规", "PyTorch/Megatron/vLLM"],
  },
  {
    company: "阶跃星辰 StepFun",
    title: "Agent基建工程师",
    direction: "Agent Infra",
    location: "北京",
    salary: "40-70K·16薪",
    seniority: "3-5 年",
    education: "本科+",
    source: "猎聘/阶跃星辰",
    link: "https://m.liepin.com/job/1985414813.shtml",
    skills: ["Agent 训推框架维护", "Agent 执行沙箱(隔离/可靠)", "Agent 实验平台(数据流水线/评测)", "Agent RL 训练链路", "terminal-use/browser-use", "轨迹采集与数据基建"],
  },
  {
    company: "阶跃星辰 StepFun",
    title: "Agent Infra开发工程师/架构师",
    direction: "Agent Infra",
    location: "上海 / 北京",
    salary: "30-60K·16薪",
    seniority: "3-5 年",
    education: "本科+",
    source: "阶跃星辰",
    link: "https://bebee.com/cn/jobs/agent-infra--techmap_cn_85414795",
    skills: ["Agent Harness 架构", "模型调用/工具执行", "上下文管理与权限控制", "Agent Loop 与 Graph Engineering", "多 Agent 协同", "可观测与评测"],
  },
  {
    company: "小红书",
    title: "【REDstar】Agent/大模型算法工程师 - rednote",
    direction: "AI Agent",
    location: "北京 / 杭州 / 上海 / 新加坡",
    salary: "面议",
    seniority: "经验不限",
    education: "本科+",
    source: "牛企直聘",
    link: "https://campus.niuqizp.com/job-vrm5aNt5L.html",
    skills: ["多语言/多模态大模型后训练", "AI Agent in 推荐算法(用户 memory/生成式召回)", "AI Agent in 搜索算法(AI 搜索/新相关性)", "跨语言跨文化交流", "ICML/NeurIPS/ACL 顶会优先", "Java/C++/Python"],
  },
  {
    company: "快手",
    title: "【快Star】Agent智能创作算法研究员-【可灵AI】",
    direction: "AI Agent",
    location: "深圳 / 北京",
    salary: "面议",
    seniority: "校招",
    education: "硕士+",
    source: "牛客网",
    link: "https://www.nowcoder.com/enterprise/898?pageSource=5015&page=5",
    skills: ["智能创作 Agent", "多模态/视觉生成模型", "通用 Agent 企业生产力", "RAG 增强", "多 Agent 协作", "Workflow 编排"],
  },
  {
    company: "华为",
    title: "AI工程师(27届应届生)",
    direction: "Agent Infra",
    location: "深圳",
    salary: "20-40K·16薪",
    seniority: "校招",
    education: "硕士+",
    source: "牛客网",
    link: "https://www.nowcoder.com/jobs/detail/322584",
    skills: ["企业生产办公场景 +AI", "NLP/Agent/CV/多模态落地", "企业领域知识注入与工程化", "大模型评测能力", "推理加速/量化/昇腾算子", "Python/PyTorch"],
  },
  {
    company: "小米",
    title: "顶尖应届-MiMo后训练Agent研究员-MiMo",
    direction: "AI Agent",
    location: "北京",
    salary: "15-30K·14薪",
    seniority: "应届",
    education: "硕士+",
    source: "猎聘",
    link: "https://m.liepin.com/lptjob/85239225",
    skills: ["Agent 评测体系与失败模式分析", "数据合成与筛选", "Agentic RL(奖励信号/grader/credit assignment)", "长程任务泛化与可靠性", "Self-improvement 与 Harness 协同", "MiMo-V2.6"],
  },
  {
    company: "深度求索 DeepSeek",
    title: "Agent弹性计算研发工程师（弹性计算 DSec）",
    direction: "Agent Infra",
    location: "北京 / 杭州",
    salary: "面议",
    seniority: "2-10 年",
    education: "本科+",
    source: "DeepSeek 官网",
    link: "http://talent.deepseek.com/",
    skills: ["Agent 弹性计算", "DSec 沙箱基础设施", "libdsec SDK", "沙箱隔离/资源超售", "系统栈调优", "RPC/分布式"],
  },
  {
    company: "月之暗面 Moonshot",
    title: "资深Agent研发工程师(Kimi)",
    direction: "AI Agent",
    location: "北京 / 上海",
    salary: "面议",
    seniority: "经验不限",
    education: "本科+",
    source: "月之暗面招聘",
    link: "https://jobspring.pro/job/j3957053/agent",
    skills: ["Agent 内核框架", "工程基座(可控/可查/可复现)", "工具生态 Skills/MCP/Sandbox", "Go 微服务", "PostgreSQL/Redis/ES", "K8s/CI-CD/DevOps"],
  },
  {
    company: "MiniMax",
    title: "AI Agent 服务端研发工程师-2026届",
    direction: "Agent Infra",
    location: "上海",
    salary: "面议",
    seniority: "校招",
    education: "本科+",
    source: "BOSS直聘",
    link: "https://m.zhipin.com/job_detail/331b99ec0ce847e403By29-6EFVW.html",
    skills: ["AIGC 应用服务端架构", "系统性能/稳定性/研发流程优化", "AI Native 核心代码与调优", "AI Agent 与 AI APP", "高并发服务设计", "Golang/Python"],
  },
  {
    company: "智谱 AI",
    title: "大模型后训练算法工程师(Coding Agent)",
    direction: "AI Agent",
    location: "北京",
    salary: "面议",
    seniority: "经验不限",
    education: "本科+",
    source: "BOSS直聘",
    link: "https://m.zhipin.com/job_detail/e1ccd146e810ca8403J83t28F1RV.html",
    skills: ["Coding Agent 场景优化", "GLM-5.x agentic coding", "大规模数据合成与强化学习", "长程任务规划", "评测方案设计", "后训练"],
  },
  {
    company: "百川智能",
    title: "【源点顶尖人才计划】Agent 算法工程师",
    direction: "AI Agent",
    location: "北京",
    salary: "面议",
    seniority: "应届",
    education: "本科+",
    source: "百川智能招聘",
    link: "https://campus.niuqizp.com/job-vml5aznta.html",
    skills: ["通用与领域 Agent 核心算法", "规划与推理/工具调用/记忆", "Agent Loop/Harness", "训练与强化学习", "多智能体协作/长程任务", "自学习"],
  },
  {
    company: "零一万物",
    title: "AI算法工程师(智能体)",
    direction: "AI Agent",
    location: "北京",
    salary: "面议",
    seniority: "3 年+",
    education: "硕士+",
    source: "零一万物招聘",
    link: "https://01ai.jobs.feishu.cn/index/position/7605812208450734374/detail",
    skills: ["Agent 架构", "Prompt/CoT/ToT", "Tool Use", "SFT/DPO", "多智能体协同", "RAG"],
  },
  {
    company: "面壁智能",
    title: "大模型算法工程师-智能体方向(27届校招)",
    direction: "AI Agent",
    location: "北京",
    salary: "面议",
    seniority: "校招",
    education: "本科+",
    source: "面壁智能校招",
    link: "https://miaoruzhi.com/recruitment/6ee7c25a-bb70-4497-b496-a75ad0ca6661",
    skills: ["SFT/RL", "Agent/Multi-Agent", "RAG", "文本与多模态大模型", "行业应用落地", "MiniCPM 端侧模型"],
  },
]
