// 实时职位数据 —— 由 WorkBuddy 定时自动化每日抓取并更新
// 数据来源：公开招聘平台搜索聚合（Boss直聘 / 猎聘 / 官方招聘官网 / 聚合站等）
// 注意：仅基于公开搜索结果，薪资为平台公开区间或「面议」，非全量实时数据。

// 细分方向（与「单独成列」对应，便于前端按方向筛选）
export type JobDirection = "AI Agent" | "大模型算法" | "RAG" | "多模态" | "Agent Infra"

export interface Job {
  company: string
  title: string
  direction: JobDirection
  location: string
  salary: string
  seniority: string
  education: string
  source: string
  link: string
  skills: string[]
}

// 最近一次抓取日期（YYYY-MM-DD）
export const jobsLastUpdated = "2026-09-08"

// 招聘方聚焦方向：大厂 + 头部 AI 独角兽
export const jobFocus = {
  label: "大厂 · 头部 AI 独角兽",
  companies: [
    "字节跳动", "腾讯", "阿里巴巴", "百度", "美团", "快手", "小红书", "蚂蚁集团", "华为", "小米",
    "深度求索 DeepSeek", "月之暗面 Moonshot", "MiniMax", "智谱 AI", "阶跃星辰 StepFun", "百川智能", "零一万物", "面壁智能",
  ],
}

// 抓取来源与统计口径
export const jobsStats = {
  tracked: 137, // 聚合站跟踪的 AI Agent Engineer 职位数
  companies: 76, // 覆盖公司数
  demandGrowth: "470%", // 大模型算法工程师需求同比增速
  talentGap: "8.7 万", // 大模型算法岗位人才缺口
}

// 各 AI 工程岗位薪资参考（月薪下限-上限 / 年薪参考），来源：Boss直聘·猎聘·职友集·脉脉 综合
export const salaryRanges: { role: string; monthly: string; annual: string }[] = [
  { role: "大模型算法工程师", monthly: "40-130K+", annual: "50-200 万" },
  { role: "LLMOps 工程师", monthly: "35-70K", annual: "42-84 万" },
  { role: "AI Agent 开发工程师", monthly: "15-55K", annual: "18-66 万" },
  { role: "RAG 工程师", monthly: "18-50K", annual: "22-60 万" },
]

// 当前聚合到的职位（聚焦大厂 + 头部 AI 独角兽，后续由定时任务覆盖更新）
// 抓取日期：2026-09-08，覆盖 18 家目标公司，共 25 条公开在招岗位
export const jobs: Job[] = [
  {
    company: "字节跳动",
    title: "LLM应用/Agent/AI平台研发工程师-Data",
    direction: "AI Agent",
    location: "上海",
    salary: "面议",
    seniority: "不限",
    education: "本科+",
    source: "字节跳动招聘",
    link: "https://jobs.bytedance.com/experienced/position/7634456497736534325/detail?sourceJobId=7623421136101099829",
    skills: ["Agent 编排", "Prompt 组织", "决策链路", "评测体系", "可观测基础设施"],
  },
  {
    company: "字节跳动",
    title: "AI Agent开发工程师-抖音(广州)",
    direction: "AI Agent",
    location: "广州",
    salary: "面议",
    seniority: "不限",
    education: "本科+",
    source: "字节跳动招聘",
    link: "https://jobs.bytedance.com/experienced/position/7597739886678182197/detail?sourceJobId=7506869832030390535",
    skills: ["Agent 架构", "RAG", "多模态交互", "Memory", "Multi-Agent"],
  },
  {
    company: "腾讯",
    title: "元宝搜索部-Agent算法工程师",
    direction: "多模态",
    location: "北京",
    salary: "面议",
    seniority: "3 年+",
    education: "硕士+",
    source: "腾讯招聘",
    link: "https://careers.tencent.com/jobdesc.html?postId=2066829103750889472",
    skills: ["VLM Agent", "多模态理解", "工具调用", "记忆机制", "RL 视觉推理"],
  },
  {
    company: "腾讯",
    title: "智能体应用技术算法工程师",
    direction: "AI Agent",
    location: "北京",
    salary: "面议",
    seniority: "3 年+",
    education: "本科+",
    source: "腾讯招聘",
    link: "https://careers.tencent.com/jobdesc.html?postId=2079104781984645120",
    skills: ["智能体编排", "Harness Engineering", "RAG", "Text2SQL", "Function Calling"],
  },
  {
    company: "深度求索 DeepSeek",
    title: "Agent Harness 研发工程师",
    direction: "Agent Infra",
    location: "北京",
    salary: "面议",
    seniority: "不限",
    education: "本科+",
    source: "DeepSeek 官网",
    link: "http://talent.deepseek.com/",
    skills: ["Harness", "Agent Infra", "代码智能体", "模型适配", "Agent Loop"],
  },
  {
    company: "MiniMax",
    title: "Agent 服务端 / 全栈研发工程师",
    direction: "Agent Infra",
    location: "上海 / 北京",
    salary: "面议",
    seniority: "不限",
    education: "本科+",
    source: "MiniMax 招聘官网",
    link: "https://minimaxi.com/careers",
    skills: ["Agent 全栈", "Agent 服务端", "多模态 Agent", "API 平台", "AI-native Workspace"],
  },
  {
    company: "月之暗面 Moonshot",
    title: "资深 Agent 研发工程师",
    direction: "AI Agent",
    location: "北京 / 上海",
    salary: "面议",
    seniority: "不限",
    education: "本科+",
    source: "月之暗面招聘",
    link: "https://app.mokahr.com/apply/moonshot/148506",
    skills: ["Agent 内核", "Skills", "MCP", "Sandbox", "多智能体"],
  },
  {
    company: "智谱 AI",
    title: "大模型算法工程师 - Agent 方向",
    direction: "AI Agent",
    location: "北京",
    salary: "面议",
    seniority: "校招",
    education: "硕士+",
    source: "智谱 AI 招聘",
    link: "https://zhipu-ai.jobs.feishu.cn/zhipucampus/position/list",
    skills: ["GLM", "Code Agent", "SFT/DPO", "RAG", "Agent 架构"],
  },
  {
    company: "智谱 AI",
    title: "多模态算法工程师",
    direction: "多模态",
    location: "北京",
    salary: "面议",
    seniority: "校招",
    education: "硕士/博士",
    source: "智谱 AI 招聘",
    link: "https://zhipu-ai.jobs.feishu.cn/zhipucampus/position/list",
    skills: ["多模态大模型", "预训练", "偏好对齐", "数据合成", "视频理解"],
  },
  {
    company: "阶跃星辰 StepFun",
    title: "AI Agent 算法工程师（StepStar）",
    direction: "AI Agent",
    location: "北京 / 上海",
    salary: "面议",
    seniority: "校招",
    education: "本科+",
    source: "阶跃星辰招聘",
    link: "https://www.wondercv.com/xiaozhao/stepfun-2026-spring-beijing-shanghai-7747-42fdea/",
    skills: ["DeepResearch Agent", "RL", "工具调用", "多模态", "规划与反思"],
  },
  {
    company: "百川智能",
    title: "大模型算法工程师（医疗场景 Post Training + Agent）",
    direction: "大模型算法",
    location: "北京",
    salary: "面议",
    seniority: "应届",
    education: "硕士+",
    source: "百川智能招聘",
    link: "https://www.yingjiesheng.com/job-008-053-681.html",
    skills: ["预训练", "后训练 SFT/RL", "Agent", "多模态对齐", "评测体系"],
  },
  {
    company: "零一万物",
    title: "AI算法工程师（智能体）",
    direction: "AI Agent",
    location: "北京",
    salary: "27-45K·14薪",
    seniority: "3 年+",
    education: "硕士+",
    source: "猎聘",
    link: "https://m.liepin.com/job/1984995285.shtml",
    skills: ["Agent 架构", "LangGraph", "SFT/DPO", "RAG", "多智能体"],
  },
  {
    company: "面壁智能",
    title: "大模型算法工程师-交付方向",
    direction: "AI Agent",
    location: "北京",
    salary: "面议",
    seniority: "不限",
    education: "本科+",
    source: "面壁智能招聘",
    link: "https://hiringcafe.com/job/modelbest-beijing-beijing-ngu7d5u6awxckjz6",
    skills: ["Agent/RAG 框架", "LangGraph", "Prompt Engineering", "Tool Calling", "模型部署"],
  },
  {
    company: "阿里巴巴",
    title: "千问事业部-大模型应用算法工程师(Agent 方向)",
    direction: "AI Agent",
    location: "北京",
    salary: "面议",
    seniority: "1 年+",
    education: "硕士+",
    source: "夸克招聘",
    link: "https://talent.quark.cn/off-campus/position-detail?lang=zh&positionId=7000011004&track_id=SSP1782821256884DxLMoqXcJZ8444",
    skills: ["广告 Agent", "Skills 进化", "Agentic RL", "Harness", "RAG"],
  },
  {
    company: "阿里巴巴",
    title: "千问事业部-多模态检索与agent算法专家",
    direction: "多模态",
    location: "杭州 / 北京",
    salary: "面议",
    seniority: "1 年+",
    education: "硕士+",
    source: "夸克招聘",
    link: "https://talent.quark.cn/off-campus/position-detail?lang=zh&positionId=100025920004",
    skills: ["多模态检索", "Agentic Search", "多模态 RAG", "VLM", "语义匹配"],
  },
  {
    company: "百度",
    title: "大模型算法工程师(J104493)",
    direction: "AI Agent",
    location: "北京",
    salary: "面议",
    seniority: "不限",
    education: "本科+",
    source: "百度招聘",
    link: "https://talent.baidu.com/jobs/detail/SOCIAL/57595856-2688-42e3-b21d-6e2ea6b27a22",
    skills: ["智能体系统", "ReAct/CoT", "SFT/RLHF", "RAG", "多智能体协同"],
  },
  {
    company: "美团",
    title: "大模型应用算法工程师(Agent 方向)",
    direction: "AI Agent",
    location: "北京",
    salary: "面议",
    seniority: "3 年+",
    education: "本科+",
    source: "美团招聘",
    link: "https://zhaopin.meituan.com/web/position/detail?highlightType=social&jobUnionId=3673967332",
    skills: ["Agentic RL", "Proactive Agent", "长期记忆", "RL Scaling", "复杂环境交互"],
  },
  {
    company: "美团",
    title: "大模型与智能体算法工程师",
    direction: "AI Agent",
    location: "北京 / 上海",
    salary: "面议",
    seniority: "2 年+",
    education: "硕士+",
    source: "美团招聘",
    link: "https://jobs.niuqizp.com/job-vml5NNCnM.html",
    skills: ["Function Call", "多智能体协调", "模型压缩", "Agent 评测", "工程化落地"],
  },
  {
    company: "快手",
    title: "【快Star】游戏广告Agent算法工程师",
    direction: "多模态",
    location: "北京",
    salary: "面议",
    seniority: "校招",
    education: "硕士+",
    source: "快手招聘",
    link: "https://www.shushuqiuzhi.com/job/364910",
    skills: ["大模型广告落地", "RAG", "多模态表征", "RLHF", "推荐算法"],
  },
  {
    company: "小红书",
    title: "AI Agent算法工程师(企业智能)",
    direction: "AI Agent",
    location: "北京 / 上海",
    salary: "面议",
    seniority: "1-3 年",
    education: "本科+",
    source: "小红书官网",
    link: "https://jobs.niuqizp.com/job-vYm5NN5ZC.html",
    skills: ["Agent 规划", "工具调用", "Context Engineering", "Workflow", "结果评测"],
  },
  {
    company: "小红书",
    title: "【REDstar】AI Agent算法工程师",
    direction: "AI Agent",
    location: "北京 / 上海",
    salary: "面议",
    seniority: "校招",
    education: "本科+",
    source: "小红书官网",
    link: "https://campus.niuqizp.com/job-vsm5aNNMn.html",
    skills: ["Agentic 后训练", "Memory", "Context 优化", "AI 搜索", "Agentic RL"],
  },
  {
    company: "蚂蚁集团",
    title: "大模型智能体优化算法",
    direction: "AI Agent",
    location: "北京 / 上海 / 杭州",
    salary: "面议",
    seniority: "校招",
    education: "硕士/博士",
    source: "蚂蚁集团招聘",
    link: "https://talent.antgroup.com/campus-full-list?depts=L3479",
    skills: ["Agent", "SFT/RL", "多智能体", "MCP", "后训练"],
  },
  {
    company: "华为",
    title: "agent算法工程师/研究员",
    direction: "AI Agent",
    location: "上海",
    salary: "30-60K·14薪",
    seniority: "应届",
    education: "硕士+",
    source: "华为招聘",
    link: "https://m.liepin.com/lptjob/84153729",
    skills: ["Agent Memory", "多智能体", "AI Coding", "强化学习", "下一代 Agent 架构"],
  },
  {
    company: "小米",
    title: "顶尖应届-Agent Harness算法工程师-大模型",
    direction: "Agent Infra",
    location: "北京",
    salary: "15-30K·14薪",
    seniority: "应届",
    education: "硕士+",
    source: "小米集团招聘",
    link: "https://m.liepin.com/lptjob/85239407",
    skills: ["Agent Harness", "Agentic Memory", "Agentic RL", "进化搜索", "可进化 Agent"],
  },
  {
    company: "小米",
    title: "顶尖应届-垂域Agentic大模型算法工程师-AI实验室",
    direction: "大模型算法",
    location: "北京",
    salary: "15-30K·15薪",
    seniority: "应届",
    education: "博士",
    source: "小米集团招聘",
    link: "https://m.liepin.com/lptjob/85239971",
    skills: ["垂域 Agentic", "Harness 优化", "Agentic RL", "强化微调", "多模态对齐"],
  },
]
